general_settings:
  master_key: sk_drwarbot_supersecretkey123

model_list:
  - model_name: gpt-3.5-turbo
    litellm_provider: openai
    api_key: <API_KEY>

  - model_name: gpt-4
    litellm_provider: openai
    api_key: <API_KEY>

  - model_name: claude-instant-1
    litellm_provider: anthropic
    api_key: <API_KEY>

  - model_name: gemini-pro
    litellm_provider: google
    api_key: <API_KEY>

